### ISSUE TITLE
Token expire too early

### ISSUE THREAD

**Issue by Isaac009** [amadeus4dev/developer-guides#13]
![test_api](https://user-images.githubusercontent.com/17350980/123107508-91a90480-d474-11eb-915d-a2dff00a5e82.png)
Figure 1. Laravel sample codes

![response-edited](https://user-images.githubusercontent.com/17350980/123109145-f3b63980-d475-11eb-833f-e6d70f075982.png)
Figure 2. Respond for Access Granted Client Credentials

`{
"errors": [
{
"code": 38190,
"title": "Invalid access token",
"detail": "The access token provided in the Authorization header is invalid",
"status": 401
}
]
}`

I am trying to use Amadeus APIs in laravel (PHP framework), but whenever I obtain the access_token for example in Figure 2 and use it, it produces the error above.
I tried the same information (credentials) in the postman everything works fine.
So I am wondering if the problem is my implementation in Figure 1 or something else.
I attach sample codes in Figure 1 that I used to test APIs.

**Comment by anthonyroux** [comment]
Hi,

Can you try to change the `Content-Type` of the 2nd API call (the one of `flight-destinations`), it should be `application/json` instead of `application/x-www-form-urlencoded`.
Can you try as well to print the `access_token` before including it in the header of the 2nd request to make sure it has the same content as the one returns by the first API call.
